# Generated by Django 5.2 on 2025-05-31 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pizza", "Pizza"),
                            ("drink", "Drink"),
                            ("topping", "Topping"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "image_filename",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("preparing", "Preparing"),
                            ("complete", "Complete"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(blank=True, max_length=200)),
                ("item_size", models.CharField(blank=True, max_length=20)),
                ("extra_toppings", models.TextField(blank=True)),
                ("removed_toppings", models.TextField(blank=True)),
                (
                    "total_item_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=7),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pizzeria.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuItemSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("0.33l", "0.33 L"),
                            ("0.5l", "0.5 L"),
                            ("1.5l", "1.5 L"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="pizzeria.menuitem",
                    ),
                ),
            ],
            options={
                "unique_together": {("item", "size")},
            },
        ),
        migrations.CreateModel(
            name="PizzaTopping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pizza",
                    models.ForeignKey(
                        limit_choices_to={"category": "pizza"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pizza",
                        to="pizzeria.menuitem",
                    ),
                ),
                (
                    "topping",
                    models.ForeignKey(
                        limit_choices_to={"category": "topping"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topping",
                        to="pizzeria.menuitem",
                    ),
                ),
            ],
            options={
                "unique_together": {("pizza", "topping")},
            },
        ),
    ]
