# Generated by Django 5.2 on 2025-05-31 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pizzeria", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pizzatopping",
            unique_together=set(),
        ),
    ]
